name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Upload to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name YOUR_STORAGE_ACCOUNT_NAME --auth-mode key -d '$web' -s . --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" --overwrite
